image: archlinux
packages:
  - mono
  - make
  - sass
  - mktiupgrade
  - genkfs
  - mkrom
  - patchrom
  - kpack-git
  - kimg
  - z80e
  - scas
  - knightos-kcc
  - python-pip
  - knightos-sdk
sources:
  - https://github.com/KnightOS/KnightOS
environment:
  project: KnightOS
artifacts:
  - KnightOS/bin/KnightOS-TI73.8xu
  - KnightOS/bin/KnightOS-TI83p.8xu
  - KnightOS/bin/KnightOS-TI83pSE.8xu
  - KnightOS/bin/KnightOS-TI84p.8xu
  - KnightOS/bin/KnightOS-TI84pSE.8xu
  - KnightOS/bin/KnightOS-TI84pCSE.8cu
tasks:
  - ti73: |
      cd ${project}
      knightos init --platform=TI73
      make upgrade
  - ti83p: |
      cd ${project}
      knightos init --platform=TI83p
      make clean
      make upgrade
  - ti83pse: |
      cd ${project}
      knightos init --platform=TI83pSE
      make clean
      make upgrade
  - ti84p: |
      cd ${project}
      knightos init --platform=TI84p
      make clean
      make upgrade
  - ti84pse: |
      cd ${project}
      knightos init --platform=TI84pSE
      make clean
      make upgrade
  - ti84pcse: |
      cd ${project}
      knightos init --platform=TI84pCSE
      make clean
      make upgrade
