image: archlinux
packages:
  - make
  - knightos-sass
  - mktiupgrade
  - sdl2
  - genkfs
  - patchrom
  - kpack-git
  - kimg
  - knightos-kcc
  - python-pip
  - knightos-sdk
sources:
  - https://github.com/KnightOS/KnightOS
  - https://github.com/KnightOS/mkrom
  - https://github.com/KnightOS/scas
environment:
  project: KnightOS
artifacts:
  - KnightOS/out/KnightOS-TI73.73u
  - KnightOS/out/KnightOS-TI83p.8xu
  - KnightOS/out/KnightOS-TI83pSE.8xu
  - KnightOS/out/KnightOS-TI84p.8xu
  - KnightOS/out/KnightOS-TI84pSE.8xu
  - KnightOS/out/KnightOS-TI84pCSE.8cu
tasks:
  - mkrom: |
      cd mkrom
      make
      sudo make install
  - scas: |
      cd scas
      make
      sudo make install install_man install_lib
  - ti73: |
      cd ${project}
      mkdir out
      knightos init --platform=TI73
      make upgrade
      cp bin/KnightOS-TI73.73u out/
  - ti83p: |
      cd ${project}
      knightos init --platform=TI83p
      make clean
      make upgrade
      cp bin/KnightOS-TI83p.8xu out/
  - ti83pse: |
      cd ${project}
      knightos init --platform=TI83pSE
      make clean
      make upgrade
      cp bin/KnightOS-TI83pSE.8xu out/
  - ti84p: |
      cd ${project}
      knightos init --platform=TI84p
      make clean
      make upgrade
      cp bin/KnightOS-TI84p.8xu out/
  - ti84pse: |
      cd ${project}
      knightos init --platform=TI84pSE
      make clean
      make upgrade
      cp bin/KnightOS-TI84pSE.8xu out/
  - ti84pcse: |
      cd ${project}
      knightos init --platform=TI84pCSE
      make clean
      make upgrade
      cp bin/KnightOS-TI84pCSE.8cu out/
